# Python Homework (NumPy, Pandas)

**Note**: You can create a Python file or a Jupyter Notebook file

<br>

<ins>Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.)</ins>: 
1. What does Pandas stand for?\
_Panel Data or Oython Data Analysis._

2. What are the 2 collections used in Pandas?\
_Series (1-dimensional) and DataFrame (2-dimensional)._

3. Name 4 things Pandas can do for us.\
_Data Cleansing,Statistical Analysis, Merges/Joins and Data Visulaization._

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?\
_You must use the Inplace = True parameter._

5. What is a CSV?\
_CSV stands for comma seperated values and is a plain text file containing a list of data seperaetd by values._

6. When cleaning data what values do we not like in our data?\
_Null values._

<br>

#### **Please Complete this Coding Exercise:**

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()

In [2]:
import numpy as np
arrayA = np.array ([2,3,2])
print(arrayA)

[2 3 2]


8.  Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20.

In [3]:
space = np.linspace(0, 20, num=6)
print(space)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [4]:
import copy
aspace = copy.deepcopy(space)
print(aspace)


[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [5]:
arrayB = ([[25, 16]])
arrayC = ([[11, 2], [13, 4]])
arrayD = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayB, arrayC, arrayD))
print("newArray...", newArray)



newArray... [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'

In [6]:
sortedArray = np.sort(newArray)
print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.\
\
_** ! INSTRUCED TO SKIP THIS QUESTION ! **_

13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```

In [7]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([0, 1, 2, 3, 4, 5, 6, 7])

comboArray = one + two + three
comboArray = np.sort(comboArray)
print("comboArray sorted = ", comboArray)

# or
# one = ([10, 11, 12, 13, 14, 15, 16, 17])
# two = ([20, 21, 22, 23, 24, 25, 26, 27])
# three = ([0, 1, 2, 3, 4, 5, 6, 7])

# comboArray = np.concatenate (one, two, three)
# comboArray = np.sort(comboArray)
# print("comboArray sorted = ", comboArray)

comboArray sorted =  [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [17]:
# Second element of the comboArray = 11

sec1 = comboArray[1]
print("2nd element =", sec1)

# All elements from the 3rd element = 2, to the last element = 27
sec2 = comboArray[2 : ]
print("3rd element to the last =", sec2)

# All elements from the 4th to the 14th element
sec3 = comboArray[3:14]
print("All elements from 4th - 14th =", sec3)
# checking 14th element in array
print("Checking 14th element in array = ", comboArray[13])

# Last 6 elements in array
sec4 = comboArray[-6:]
print("last 6 digits in array = ", sec4)

# 0 - 15 using negative number method
sec5 = comboArray[-24:-10]
print("0 - 15 , using negative numbers = ", sec5)

#  From 20 every even element to the end
sec6 = comboArray[16: -1: 2]
print("Count by 2's starting at 20", sec6) 

# or
# for i in range(len(sec6)):
#     if(sec6[i]%2==0):
#         print(sec6[i])

# from the last element moving forward, every 5th element
sec7 = comboArray [3: : 5]
print("Count by 5's to last element", sec7)

2nd element = 1
3rd element to the last = [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
All elements from 4th - 14th = [ 3  4  5  6  7 10 11 12 13 14 15]
Checking 14th element in array =  15
last 6 digits in array =  [22 23 24 25 26 27]
0 - 15 , using negative numbers =  [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
Count by 2's starting at 20 [20 22 24 26]
Count by 5's to last element [ 3 10 15 22 27]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [34]:
import pandas as pd

Ingredients = ["Flour", "Milk", "Eggs", "Spam"]
Quantity = [4, 1, 2, 1]
Unit = ["cups", "cup", "large","can"] 

Ingredients = pd.Series(Ingredients)
Quantity = pd.Series(Quantity)
Unit = pd.Series(Unit)


# print(Ingredients)
# print(Quantity)
# print(Unit)

df = pd.concat([Ingredients, Quantity, Unit], axis = 1,)

# Assign column headers
df.columns = ["Ingredients", "Quantity","Unit"]
df


Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [75]:
Data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pd.DataFrame(Data)
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
        

In [76]:
studentData["deserts"] = ["ice cream", "Cashew Fudge", "waffles", "Carrot Hawla"]
studentData

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffles  
3  Carrot Hawla

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"


In [78]:
studentData.sort_values(by = ["Name","address"], inplace = True)
studentData


Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Hawla  
2       waffles  
0     ice cream  
1  Cashew Fudge

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [80]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df

df.to_csv("cows_and_goats.csv")


20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [90]:
import pandas as pd

dfveg = {"Vegetables": ["Lettuce", "Spinach", "Celery", "Cucumber", "Radishes", "Zuchinni", "Mushroom", "Corn", "Sweet Potato", "Peas" ],
              "Calories" : [5, 7, 14, 16, 18, 19, 21, 177, 129, 118]}

Vegetables = pd.DataFrame(dfveg)
Vegetables

Vegetables.to_csv("Vegetables.csv")

Vegetables.sort_values(by = ["Calories", "Vegetables"], inplace = True)
Vegetables

Vegetables.to_csv("Vegetables2.csv")
